name: Master

on:
  push:
    branches:
      - master

jobs:
  test_build:
    name: Test and Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: npm run test

      - run: npm run build
